Change the error message for colliding class/interface/trait names to be a little more clearer.
  C:\> php -r "interface stdClass { }"
  Error: Cannot declare interface stdClass, because the name is already in use in Command Line Code on line 1